# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
cities_path = "weatherpy_data.csv"
city_data_df = pd.read_csv(cities_path)
city_data_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,hobart,-42.8794,147.3294,70.11,87,20,2.30,AU,1643661948
1,mayo,38.8876,-76.5119,38.89,56,100,5.99,US,1643662099
2,rikitea,-23.1203,-134.9692,77.49,65,99,4.54,PF,1643662100
3,mataura,-46.1927,168.8643,66.47,67,38,1.81,NZ,1643661947
4,roald,62.5833,6.1333,33.01,86,20,13.80,NO,1643662100

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [13]:
gmaps.configure(api_key = g_key)
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
#figure_layout = {
#    'width': '10000 px',
#    'height': '1000 px',
#}
#fig = gmaps.figure(layout = figure_layout)
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights = humidity, dissipating = False, max_intensity = 300,point_radius = 5)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [4]:
#Create a copy of the dataframe
copy_city_data = city_data_df.copy()

#Select the data that has a max temp > 70, max_temp < 80 and wind speed < 10
copy_city_data = copy_city_data[(copy_city_data["Max Temp"] > 70) & (copy_city_data["Max Temp"] < 80) & (copy_city_data["Wind Speed"] < 10)] 

#Then also introduce a filter to have only the cities with cloudiness = 0
copy_city_data = copy_city_data[(copy_city_data["Cloudiness"] == 0)]

#Drop any rows where it has at least one NA
copy_city_data.dropna(how ='any')

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
31,cape town,-33.9258,18.4232,78.12,77,0,1.99,ZA,1643661465
48,kapaa,22.0752,-159.3190,77.47,70,0,1.01,US,1643661383
98,ixtapa,20.7000,-105.2000,78.03,53,0,8.05,MX,1643662121
134,brawley,32.9787,-115.5303,73.18,20,0,3.44,US,1643661976
211,cabo san lucas,22.8909,-109.9124,79.90,60,0,1.99,MX,1643662102
231,beroroha,-21.6667,45.1667,75.49,57,0,5.12,MG,1643662155
242,lakes entrance,-37.8811,147.9810,76.15,76,0,6.20,AU,1643662105
305,praia,14.9215,-23.5087,70.34,83,0,8.05,CV,1643662172
316,salalah,17.0151,54.0924,71.69,68,0,5.75,OM,1643662176
385,alamogordo,32.8995,-105.9603,70.39,23,0,1.01,US,1643662051
421,luanda,-8.8368,13.2343,78.80,78,0,9.22,AO,1643662014
500,kahului,20.8947,-156.4700,79.97,62,0,0.00,US,1643662044
509,gwadar,25.1216,62.3254,71.49,68,0,4.74,PK,1643662225

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [28]:
hotel_df = copy_city_data[["City", "Country", "Lat", "Lng"]]
hotel_df["Hotel Name"] = ""
count = 0

# params dictionary to update each iteration
params = {
    "radius": 5000,
    "types": "hotel",
    "keyword": "hotel",
    "key": g_key
}

# Use the lat/lng we recovered to identify airports
for index, row in hotel_df.iterrows():
        # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]
    
     # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    # Use the search term: "International Airport" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # make request and print url
    name_address = requests.get(base_url, params=params)
    #print(name_address.url)
    
    # convert to json
    name_address = name_address.json()
    
    # Since some data may be missing we incorporate a try-except to skip any that are missing a data point.
    try:
        hotel_df.loc[index, "Hotel Name"] = name_address["results"][0]["name"]
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

C:\Users\carlalorente\Anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\carlalorente\Anaconda3\envs\pythondata\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

Missing field/result... skipping.

In [31]:
# Visualize to confirm airport data appears
print(len(hotel_df))
hotel_df = hotel_df.reset_index()
hotel_df.head()

13

,index,City,Country,Lat,Lng,Hotel Name
0,31,cape town,ZA,-33.9258,18.4232,"Radisson Blu Hotel Waterfront, Cape Town"
1,48,kapaa,US,22.0752,-159.3190,Hotel Coral Reef
2,98,ixtapa,MX,20.7000,-105.2000,Flamingo Vallarta Hotel & Marina
3,134,brawley,US,32.9787,-115.5303,Brawley Inn Hotel & Conference Center
4,211,cabo san lucas,MX,22.8909,-109.9124,Solmar Resort

In [32]:
#Restrict to only 10 hotels

hotel_df = hotel_df.loc[0:10,:]
print(len(hotel_df))

11

In [33]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [34]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [ ]:
plt.savefig("Hotel_Heatmap.png");